import { EMAIL } from '../fixtures/constants';
const faker = require('faker');

let firstName = faker.name.firstName();
let lastName = faker.name.lastName();
let email = faker.internet.email();
let password = faker.internet.password();

describe('Register module', () => {

    before(() => {
        cy.visit('/')
    })

    beforeEach(() => {
        cy.visit('/')
        cy.get('.nav-link').contains('Register').click()
    })

    it('GA-9 : Register page test', () => {
        cy.get('.container > div > h1.title-style')
            .should('be.visible')
            .should('have.text', 'Register')
        cy.get('form > div.form-group:nth-child(1) > label')
            .should('have.text', 'First Name')
            .should('be.visible')
            .should('have.attr', 'for', 'first-name')
        cy.get('form > div.form-group:nth-child(1) > input#first-name')
            .should('have.class', 'form-control')
            .should('be.visible')
            .should('have.attr', 'required', 'required')
            .should('have.attr', 'type', 'text')
        cy.get('form > div.form-group:nth-child(2) > label')
            .should('have.text', 'Last Name')
            .should('be.visible')
            .should('have.attr', 'for', 'last-name')
        cy.get('form > div.form-group:nth-child(2) > input#last-name')
            .should('have.class', 'form-control')
            .should('be.visible')
            .should('have.attr', 'required', 'required')
            .should('have.attr', 'type', 'text')
        cy.get('form > div.form-group:nth-child(3) > label')
            .should('have.text', 'Email')
            .should('be.visible')
            .should('have.attr', 'for', 'email')
        cy.get('form > div.form-group:nth-child(3) > input#email')
            .should('have.class', 'form-control')
            .should('be.visible')
            .should('have.attr', 'required', 'required')
            .should('have.attr', 'type', 'email')
        cy.get('form > div.form-group:nth-child(4) > label')
            .should('have.text', 'Password')
            .should('be.visible')
            .should('have.attr', 'for', 'password')
        cy.get('form > div.form-group:nth-child(4) > input#password')
            .should('have.class', 'form-control')
            .should('be.visible')
            .should('have.attr', 'required', 'required')
            .should('have.attr', 'type', 'password')
        cy.get('form > div.form-group:nth-child(5) > label')
            .should('have.text', 'Confirmed Password')
            .should('be.visible')
            .should('have.attr', 'for', 'password-confirmation')
        cy.get('form > div.form-group:nth-child(5) > input#password-confirmation')
            .should('have.class', 'form-control')
            .should('be.visible')
            .should('have.attr', 'required', 'required')
            .should('have.attr', 'type', 'password')
        cy.get('form > div.form-group:nth-child(6) > input')
            .should('have.class', 'form-check-input')
            .should('be.visible')
            .should('have.attr', 'type', 'checkbox')
        cy.get('form > div.form-group:nth-child(6) > label')
            .should('have.text', 'Accepted terms and conditions')
            .should('be.visible')
            .should('have.class', 'form-check-label')
        cy.get('form > button')
            .should('have.class', 'btn')
            .should('have.class', 'btn-custom')
            .should('be.visible')
            .should('have.text', 'Submit')
    })

    it('First Name empty', () => {
        cy.get('form > div.form-group:nth-child(2) > input#last-name').type(lastName)
        cy.get('form > div.form-group:nth-child(3) > input#email').type(email)
        cy.get('form > div.form-group:nth-child(4) > input#password').type(password)
        cy.get('form > div.form-group:nth-child(5) > input#password-confirmation').type(password)
        cy.get('form > div.form-group:nth-child(6) > input').click()
        cy.get('form > button').click()
        cy.get('form > div.form-group:nth-child(1) > input#first-name').should('have.focus')
    })

    it('Last Name empty', () => {
        cy.get('form > div.form-group:nth-child(1) > input#first-name').type(firstName)
        cy.get('form > div.form-group:nth-child(3) > input#email').type(email)
        cy.get('form > div.form-group:nth-child(4) > input#password').type(password)
        cy.get('form > div.form-group:nth-child(5) > input#password-confirmation').type(password)
        cy.get('form > div.form-group:nth-child(6) > input').click()
        cy.get('form > button').click()
        cy.get('form > div.form-group:nth-child(2) > input#last-name').should('have.focus')
    })

    it('Email empty', () => {
        cy.get('form > div.form-group:nth-child(1) > input#first-name').type(firstName)
        cy.get('form > div.form-group:nth-child(2) > input#last-name').type(lastName)
        cy.get('form > div.form-group:nth-child(4) > input#password').type(password)
        cy.get('form > div.form-group:nth-child(5) > input#password-confirmation').type(password)
        cy.get('form > div.form-group:nth-child(6) > input').click()
        cy.get('form > button').click()
        cy.get('form > div.form-group:nth-child(3) > input#email').should('have.focus')
    })

    it('Password empty', () => {
        cy.get('form > div.form-group:nth-child(1) > input#first-name').type(firstName)
        cy.get('form > div.form-group:nth-child(2) > input#last-name').type(lastName)
        cy.get('form > div.form-group:nth-child(3) > input#email').type(email)
        cy.get('form > div.form-group:nth-child(5) > input#password-confirmation').type(password)
        cy.get('form > div.form-group:nth-child(6) > input').click()
        cy.get('form > button').click()
        cy.get('form > div.form-group:nth-child(4) > input#password').should('have.focus')
    })

    it('Password Confirmation empty', () => {
        cy.get('form > div.form-group:nth-child(1) > input#first-name').type(firstName)
        cy.get('form > div.form-group:nth-child(2) > input#last-name').type(lastName)
        cy.get('form > div.form-group:nth-child(3) > input#email').type(email)
        cy.get('form > div.form-group:nth-child(4) > input#password').type(password)
        cy.get('form > div.form-group:nth-child(6) > input').click()
        cy.get('form > button').click()
        cy.get('form > div.form-group:nth-child(5) > input#password-confirmation').should('have.focus')
    })

    it('Password one letter', () => {
        cy.get('form > div.form-group:nth-child(1) > input#first-name').type(firstName)
        cy.get('form > div.form-group:nth-child(2) > input#last-name').type(lastName)
        cy.get('form > div.form-group:nth-child(3) > input#email').type(email)
        cy.get('form > div.form-group:nth-child(4) > input#password').type('a')
        cy.get('form > div.form-group:nth-child(5) > input#password-confirmation').type(password)
        cy.get('form > div.form-group:nth-child(6) > input').click()
        cy.get('form > button').click()
        cy.get('.alert').should('have.text', 'The password must be at least 8 characters.')
                        .should('be.visible')
                        .should('have.class', 'alert')
    })

    it('Password and password confirmation one letter', () => {
        cy.get('form > div.form-group:nth-child(1) > input#first-name').type(firstName)
        cy.get('form > div.form-group:nth-child(2) > input#last-name').type(lastName)
        cy.get('form > div.form-group:nth-child(3) > input#email').type(email)
        cy.get('form > div.form-group:nth-child(4) > input#password').type('a')
        cy.get('form > div.form-group:nth-child(5) > input#password-confirmation').type('a')
        cy.get('form > div.form-group:nth-child(6) > input').click()
        cy.get('form > button').click()
        cy.get('.alert').should('have.text', 'The password must be at least 8 characters.')
                        .should('be.visible')
                        .should('have.class', 'alert')
    })

    it('Password confirmation one letter', () => {
        cy.get('form > div.form-group:nth-child(1) > input#first-name').type(firstName)
        cy.get('form > div.form-group:nth-child(2) > input#last-name').type(lastName)
        cy.get('form > div.form-group:nth-child(3) > input#email').type(email)
        cy.get('form > div.form-group:nth-child(4) > input#password').type(password)
        cy.get('form > div.form-group:nth-child(5) > input#password-confirmation').type('a')
        cy.get('form > div.form-group:nth-child(6) > input').click()
        cy.get('form > button').click()
        cy.get('.alert').should('have.text', 'The password confirmation does not match.')
                        .should('be.visible')
                        .should('have.class', 'alert')
    })

    it('Password format invalid', () => {
        cy.get('form > div.form-group:nth-child(1) > input#first-name').type(firstName)
        cy.get('form > div.form-group:nth-child(2) > input#last-name').type(lastName)
        cy.get('form > div.form-group:nth-child(3) > input#email').type(email)
        cy.get('form > div.form-group:nth-child(4) > input#password').type('aabbccdd')
        cy.get('form > div.form-group:nth-child(5) > input#password-confirmation').type(password)
        cy.get('form > div.form-group:nth-child(6) > input').click()
        cy.get('form > button').click()
        cy.get('.alert').should('have.text', 'The password confirmation does not match.')
                        .should('be.visible')
                        .should('have.class', 'alert')
    })

    it('Terms and conditions unchecked', () => {
        cy.get('form > div.form-group:nth-child(1) > input#first-name').type(firstName)
        cy.get('form > div.form-group:nth-child(2) > input#last-name').type(lastName)
        cy.get('form > div.form-group:nth-child(3) > input#email').type(email)
        cy.get('form > div.form-group:nth-child(4) > input#password').type(password)
        cy.get('form > div.form-group:nth-child(5) > input#password-confirmation').type(password)
        cy.get('form > button').click()
        cy.get('.alert').should('have.text', 'The terms and conditions must be accepted.')
                        .should('be.visible')
                        .should('have.class', 'alert')
    })

    it('Email invalid format', () => {
        cy.get('form > div.form-group:nth-child(1) > input#first-name').type(firstName)
        cy.get('form > div.form-group:nth-child(2) > input#last-name').type(lastName)
        cy.get('form > div.form-group:nth-child(3) > input#email').type('test@test')
        cy.get('form > div.form-group:nth-child(4) > input#password').type(password)
        cy.get('form > div.form-group:nth-child(5) > input#password-confirmation').type(password)
        cy.get('form > div.form-group:nth-child(6) > input').click()
        cy.get('form > button').click()
        cy.get('.alert').should('have.text', 'The email must be a valid email address.')
                        .should('be.visible')
                        .should('have.class', 'alert')
    })

    it('GA-84 : User can\'t register twice #1', () => {
        cy.get('form > div.form-group:nth-child(1) > input#first-name').type(firstName)
        cy.get('form > div.form-group:nth-child(2) > input#last-name').type(lastName)
        cy.get('form > div.form-group:nth-child(3) > input#email').type(email)
        cy.get('form > div.form-group:nth-child(4) > input#password').type(password)
        cy.get('form > div.form-group:nth-child(5) > input#password-confirmation').type(password)
        cy.get('form > div.form-group:nth-child(6) > input').click()
        cy.get('form > button').click()
    })

    it('GA-84 : User can\'t register twice #2', () => {
        cy.get('form > div.form-group:nth-child(1) > input#first-name').clear()
        cy.get('form > div.form-group:nth-child(2) > input#last-name').clear()
        cy.get('form > div.form-group:nth-child(3) > input#email').clear()
        cy.get('form > div.form-group:nth-child(4) > input#password').clear()
        cy.get('form > div.form-group:nth-child(5) > input#password-confirmation').clear()
        cy.get('form > div.form-group:nth-child(6) > input').click()

    })

    it('GA-84 : User can\'t register twice #3', () => {
        cy.get('form > div.form-group:nth-child(1) > input#first-name').type(firstName)
        cy.get('form > div.form-group:nth-child(2) > input#last-name').type(lastName)
        cy.get('form > div.form-group:nth-child(3) > input#email').type(email)
        cy.get('form > div.form-group:nth-child(4) > input#password').type(password)
        cy.get('form > div.form-group:nth-child(5) > input#password-confirmation').type(password)
        cy.get('form > div.form-group:nth-child(6) > input').click()
        cy.get('form > button').click()

        cy.get('.alert').should('have.text', 'The email has already been taken.')
                        .should('be.visible')
                        .should('have.class', 'alert')
    })
})